### ISSUE TITLE
Return U+0022 Quotation Marks

### ISSUE THREAD

**Issue by joshpetit** [BertrandSim/esv-in-vim#1]
Hello! Thank you for this vim plugin, it's been really nice to use for quick lookups. The only difficulty I have is with the chosen encoding for the quotes. This is minor, but all quotes are returned as U+201C, example:
![image](https://user-images.githubusercontent.com/59021155/91509817-5025e800-e8a9-11ea-9f68-3449ef8df143.png)
I'm sure this is just because of the way it's returned by the API, but it would be a nice minor bug fix to change it to the usual " since the curved quotes don't allow interaction in vim (the standard U+0022 quote ( " ) doesn't just map to the curved quote).

This is obviously not a deal-breaker or anything but would be a nice tweak.

**Comment by BertrandSim** [comment]
Hi @joshpetit, 

Thanks for pointing this out! I just pushed a branch unsmart_quotes. Could you check it out?

I've also done the change for single quotes as well.

You can re-enable curly quotes again with `let g:esv_smart_single_quotes=1` and `let g:esv_smart_double_quotes=1`.

**Comment by joshpetit** [comment]
Ok @BertrandSim, I cloned it and it works great! Thanks!

**Comment by BertrandSim** [comment]
Great! In that case I'll merge the branch mentioned above into master. Thanks again :)
